; Listing generated by Microsoft (R) Optimizing Compiler Version 19.40.33808.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__62AC66AD_concurrencysal@h DB 01H
__4E275427_sal@h DB 01H
__3349D93D_vadefs@h DB 01H
__2148C846_vcruntime@h DB 01H
__C5958D5B_xkeycheck@h DB 01H
__5B45A020_yvals_core@h DB 01H
__F5329964_limits@h DB 01H
__AF5F685F_climits DB 01H
__1B0272D9_corecrt@h DB 01H
__0F1CA72C_vcruntime_new@h DB 01H
__E67C0522_vcruntime_new_debug@h DB 01H
__935DC21B_crtdbg@h DB 01H
__41F31A22_crtdefs@h DB 01H
__C9E10474_use_ansi@h DB 01H
__9DF0FC12_yvals@h DB 01H
__BB16330F_corecrt_math@h DB 01H
__3BF2A406_math@h DB 01H
__45DED006_corecrt_malloc@h DB 01H
__13F5961F_stddef@h DB 01H
__FD6DBD68_corecrt_search@h DB 01H
__E2E33A61_corecrt_wstdlib@h DB 01H
__6E5ACABA_stdlib@h DB 01H
__2BB04AAD_cstdlib DB 01H
__32EF363D_xtr1common DB 01H
__93354958_intrin0@inl@h DB 01H
__58DEA329_intrin0@h DB 01H
__2C9D5A90_cmath DB 01H
__44420885_corecrt_stdio_config@h DB 01H
__AB601D8D_corecrt_wstdio@h DB 01H
__C1EC35D3_stdio@h DB 01H
__90046EA8_cstdio DB 01H
__61CC25A1_errno@h DB 01H
__78840DBF_vcruntime_string@h DB 01H
__E4C945B4_corecrt_memcpy_s@h DB 01H
__8EAFF484_corecrt_memory@h DB 01H
__6490AEC5_corecrt_wstring@h DB 01H
__E8295E1E_string@h DB 01H
__6722E24D_cstring DB 01H
__EF1F6BBA_corecrt_wconio@h DB 01H
__74484FB3_corecrt_wctype@h DB 01H
__3D1D430C_corecrt_wdirect@h DB 01H
__8ECB7138_corecrt_share@h DB 01H
__DB7FEBA6_corecrt_wio@h DB 01H
__9A9F0068_corecrt_wprocess@h DB 01H
__369A9BC3_corecrt_wtime@h DB 01H
__CE789B9D_types@h DB 01H
__9901C817_stat@h DB 01H
__3FCAD62E_wchar@h DB 01H
__0A8FB8FB_cwchar DB 01H
__494F3DCD_iosfwd DB 01H
__8E7B9000_cstddef DB 01H
__786A109E_initializer_list DB 01H
__4B44B75B_stdint@h DB 01H
__96EEABD0_cstdint DB 01H
__8B3C4B90_type_traits DB 01H
__1CBDCF26_utility DB 01H
__9C80152E___msvc_iter_core@hpp DB 01H
__279CCFA6_xutility DB 01H
__363078E6_iterator DB 01H
__F7972D0B_share@h DB 01H
__64144EAC___msvc_system_error_abi@hpp DB 01H
__0D251A53_cerrno DB 01H
__FA77ED4C_malloc@h DB 01H
__89766DA4_corecrt_terminate@h DB 01H
__04848964_eh@h DB 01H
__EE920070_vcruntime_exception@h DB 01H
__89AC74B4_exception DB 01H
__04698573___msvc_sanitizer_annotate_container@hpp DB 01H
__B9985323_float@h DB 01H
__E340A52F_cfloat DB 01H
__85A6E84B_limits DB 01H
__F4E30912_new DB 01H
__83A0F862_xatomic@h DB 01H
__7628ACE5_xmemory DB 01H
__02FB2A79_xstring DB 01H
__00E24EE9_stdexcept DB 01H
__18DD7E70_xcall_once@h DB 01H
__3565E91D_xerrc@h DB 01H
__0A9237D2_time@h DB 01H
__EA2EC698_ctime DB 01H
__91582CE7_xtimec@h DB 01H
__A8AF33C7_xthreads@h DB 01H
__EE93B489_atomic DB 01H
__A7806C50_system_error DB 01H
__886EF3B1_vcruntime_typeinfo@h DB 01H
__57433CBF_typeinfo DB 01H
__3908E4C5_memory DB 01H
__154DB3CA_xfacet DB 01H
__4C585D2A___msvc_xlocinfo_types@hpp DB 01H
__1EC467ED_ctype@h DB 01H
__9FCF890F_cctype DB 01H
__791C33B7_locale@h DB 01H
__B81C967C_clocale DB 01H
__48CADF77_xlocinfo DB 01H
__DDC55E48_xlocale DB 01H
__712FA864_xiosbase DB 01H
__0242F655_streambuf DB 01H
__4342385F_xlocnum DB 01H
__0C2E3304_ios DB 01H
__CED5848C_ostream DB 01H
__AD05B1B6_istream DB 01H
__45E5B5B9_iostream DB 01H
__D734F2B8_Main@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	main
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_0N@GCDOMLDM@Hello?5World?$CB@		; `string'
EXTRN	__imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ:PROC
EXTRN	?Log@@YAXPEBD@Z:PROC				; Log
EXTRN	__CheckForDebuggerJustMyCode:PROC
EXTRN	__imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A:BYTE
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN4
	DD	imagerel $LN4+48
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT ??_C@_0N@GCDOMLDM@Hello?5World?$CB@
CONST	SEGMENT
??_C@_0N@GCDOMLDM@Hello?5World?$CB@ DB 'Hello World!', 00H ; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
main	PROC						; COMDAT
; File C:\Users\v_runzhiguo\Desktop\Dev-CPP\HelloWorld1\HelloWorld1\Main.cpp
; Line 5
$LN4:
	sub	rsp, 40					; 00000028H
	lea	rcx, OFFSET FLAT:__D734F2B8_Main@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rcx, OFFSET FLAT:??_C@_0N@GCDOMLDM@Hello?5World?$CB@
	call	?Log@@YAXPEBD@Z				; Log
	mov	rcx, QWORD PTR __imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A
	call	QWORD PTR __imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ
	xor	eax, eax
; Line 8
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 8
__formal$ = 16
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\v_runzhiguo\Desktop\Dev-CPP\HelloWorld1\HelloWorld1\Main.cpp
	lea	rcx, OFFSET FLAT:__D734F2B8_Main@cpp
	jmp	__CheckForDebuggerJustMyCode
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 8
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\v_runzhiguo\Desktop\Dev-CPP\HelloWorld1\HelloWorld1\Main.cpp
	lea	rcx, OFFSET FLAT:__D734F2B8_Main@cpp
	jmp	__CheckForDebuggerJustMyCode
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
